# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SbomexAT0036 < Formula
  desc "sbomex is a command line utility to help query and pull from Interlynk public SBOM"
  homepage "https://github.com/kchetans/sbomex"
  version "0.0.36"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.36/sbomex-darwin-arm64"
      sha256 "005f5de00b050dbf8001571147853afb005aa55d464707596efc4bfb6936740b"

      def install
        bin.install "sbomex-darwin-arm64" => "sbomex-darwin-arm64"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.36/sbomex-darwin-amd64"
      sha256 "b4731c2a863288decaf8eb58a472d6a15149d20235621283a0f36d64dcd1fc7b"

      def install
        bin.install "sbomex-darwin-amd64" => "sbomex-darwin-amd64"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.36/sbomex-linux-amd64"
      sha256 "a9aad0a94c9d6fa0b16e7ace5fa2027962b3066fb2cd5694b07b42fe0e7a8f5e"

      def install
        bin.install "sbomex-linux-amd64" => "sbomex-linux-amd64"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.36/sbomex-linux-arm64"
      sha256 "e73e81435f841e40cc90bf2c1627b54ceb4238e4d85693287c6925e4bbd84ddf"

      def install
        bin.install "sbomex-linux-arm64" => "sbomex-linux-arm64"
      end
    end
  end
end
