# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SbomexAT0025 < Formula
  desc "sbomex is a command line utility to help query and pull from Interlynk public SBOM"
  homepage "https://github.com/kchetans/sbomex"
  version "0.0.25"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.25/sbomex-darwin-arm64"
      sha256 "3dac77b335a430a135cfa16610f8a738cd83d87b3bf21ba65e2b7e7dc7465697"

      def install
        bin.install "sbomex-darwin-arm64" => "sbomex-darwin-arm64"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.25/sbomex-darwin-amd64"
      sha256 "1c5baa6280aa18390e227d0b86aa18a9717037ed8d498d7c263afac15c7f90af"

      def install
        bin.install "sbomex-darwin-amd64" => "sbomex-darwin-amd64"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.25/sbomex-linux-amd64"
      sha256 "6e706e7c0f0df4b190dfa9d6069625d156c11c191ac62343a1f0a33b1921dab0"

      def install
        bin.install "sbomex-linux-amd64" => "sbomex-linux-amd64"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.25/sbomex-linux-arm64"
      sha256 "fb7aa737466c2b397ba99f17f4daa1d13adc75d51fefcb07d312b999d26db3c5"

      def install
        bin.install "sbomex-linux-arm64" => "sbomex-linux-arm64"
      end
    end
  end
end
