# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SbomexAT0023 < Formula
  desc "sbomex is a command line utility to help query and pull from Interlynk public SBOM"
  homepage "https://github.com/kchetans/sbomex"
  version "0.0.23"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.23/sbomex-darwin-arm64"
      sha256 "2f8bac4315dca590453bce957efae1b228595d678a7f2ed4ef6df0b70adfc4b0"

      def install
        bin.install "sbomex-darwin-arm64" => "sbomex-darwin-arm64"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.23/sbomex-darwin-amd64"
      sha256 "6d7d2ba60e2edbdad9e90a2b96c991e478973c29a15176ae64c4f0e4b83da1a9"

      def install
        bin.install "sbomex-darwin-amd64" => "sbomex-darwin-amd64"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.23/sbomex-linux-arm64"
      sha256 "5547032d28bf5227bf7b4b3d2ddef4448c4d4b4b3e4415473bc61c806749282c"

      def install
        bin.install "sbomex-linux-arm64" => "sbomex-linux-arm64"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.23/sbomex-linux-amd64"
      sha256 "fc6ee8a8f547485aa466050338ebc4aa6e2e118897a1026e632d44742309783b"

      def install
        bin.install "sbomex-linux-amd64" => "sbomex-linux-amd64"
      end
    end
  end
end
