# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SbomexAT0024 < Formula
  desc "sbomex is a command line utility to help query and pull from Interlynk public SBOM"
  homepage "https://github.com/kchetans/sbomex"
  version "0.0.24"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.24/sbomex-darwin-arm64"
      sha256 "e1633c8a6afaba30b3a6d412a799874405d4acbd5b4505875a382c0a8f8336cc"

      def install
        bin.install "sbomex-darwin-arm64" => "sbomex-darwin-arm64"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.24/sbomex-darwin-amd64"
      sha256 "3533528e8b6b2baab51dc09f42fa7afa528cc09527f07ca5358992c4c1d9bdf7"

      def install
        bin.install "sbomex-darwin-amd64" => "sbomex-darwin-amd64"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.24/sbomex-linux-amd64"
      sha256 "3149f6a9b5833040d903be81ab78d71b32783c3fda182509ec5a98cb2549df8e"

      def install
        bin.install "sbomex-linux-amd64" => "sbomex-linux-amd64"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.24/sbomex-linux-arm64"
      sha256 "a31bdfb962fdadf508e6f42c8068ac327c423dc1355b77b885da59c35b5eed5e"

      def install
        bin.install "sbomex-linux-arm64" => "sbomex-linux-arm64"
      end
    end
  end
end
